DATA_PATH = "data"

CSV_PATH = f"{DATA_PATH}/csv"
CSV_EXT = ".csv"

COFOUNDER_INVESTMENT = "cofounders_with_investment_managers"
COFOUNDER_INVESTMENT_CSV = f"{COFOUNDER_INVESTMENT}{CSV_EXT}"

PORTFOLIO = "portfolio_links"
PORTFOLIO_CSV = f"{PORTFOLIO}{CSV_EXT}"

TEAM = "employees_team"
TEAM_CSV = f"{TEAM}{CSV_EXT}"

TEAM_LINKEDIN = "employees_linkedin"
TEAM_LINKEDIN_CSV = f"{TEAM_LINKEDIN}{CSV_EXT}"

LOOKUP_LINKEDIN = "employee_lookup_linkedin"
LOOKUP_LINKEDIN_CSV = f"{LOOKUP_LINKEDIN}{CSV_EXT}"

EDUCATION = "education"
EXPERIENCE = "experience"
VOLUNTEERING = "volunteering-experiences"

COFOUNDER = "cofounders"
COFOUNDER_LINKEDIN = f"{COFOUNDER}_linkedin"

COFOUNDER_MAIN = f"{COFOUNDER_LINKEDIN}_main"
COFOUNDER_MAIN_CSV = f"{COFOUNDER_MAIN}{CSV_EXT}"

COFOUNDER_EDU = f"{COFOUNDER_LINKEDIN}_{EDUCATION}"
COFOUNDER_EDU_CSV = f"{COFOUNDER_EDU}{CSV_EXT}"

COFOUNDER_EXP = f"{COFOUNDER_LINKEDIN}_{EXPERIENCE}"
COFOUNDER_EXP_CSV = f"{COFOUNDER_EXP}{CSV_EXT}"

COFOUNDER_VOL = f"{COFOUNDER_LINKEDIN}_{VOLUNTEERING}"
COFOUNDER_VOL_CSV = f"{COFOUNDER_VOL}{CSV_EXT}"

EMPLOYEE = "employee"
EMPLOYEE_LINKEDIN = f"{EMPLOYEE}_linkedin"

EMPLOYEE_MAIN = f"{EMPLOYEE_LINKEDIN}_main"
EMPLOYEE_MAIN_CSV = f"{EMPLOYEE_MAIN}{CSV_EXT}"

EMPLOYEE_EDU = f"{EMPLOYEE_LINKEDIN}_{EDUCATION}"
EMPLOYEE_EDU_CSV = f"{EMPLOYEE_EDU}{CSV_EXT}"

EMPLOYEE_EXP = f"{EMPLOYEE_LINKEDIN}_{EXPERIENCE}"
EMPLOYEE_EXP_CSV = f"{EMPLOYEE_EXP}{CSV_EXT}"

EMPLOYEE_VOL = f"{EMPLOYEE_LINKEDIN}_{VOLUNTEERING}"
EMPLOYEE_VOL_CSV = f"{EMPLOYEE_VOL}{CSV_EXT}"

DETAILS_LINKEDIN = "/details"
EDUCATION_LINKEDIN = f"{DETAILS_LINKEDIN}/{EDUCATION}"
EXPERIENCE_LINKEDIN = f"{DETAILS_LINKEDIN}/{EXPERIENCE}"
VOLUNTEERING_LINKEDIN = f"{DETAILS_LINKEDIN}/{VOLUNTEERING}"

GEPHI_PATH = f"{DATA_PATH}/gephi"
GEPHI_EXT = ".gexf"

VC_COMPANY = "vc_company"
VC_COMPANY_GEPHI = f"{VC_COMPANY}{GEPHI_EXT}"

COMPANY_COFOUNDER = "company_cofounder"
COMPANY_COFOUNDER_GEPHI = f"{COMPANY_COFOUNDER}{GEPHI_EXT}"

COMPANY_INV_MANAGER = "company_investment_manager"
COMPANY_INV_MANAGER_GEPHI = f"{COMPANY_INV_MANAGER}{GEPHI_EXT}"

COFOUNDER_EDU_GEPHI = f"{COFOUNDER}_{EDUCATION}{GEPHI_EXT}"
COFOUNDER_EXP_GEPHI = f"{COFOUNDER}_{EXPERIENCE}{GEPHI_EXT}"
COFOUNDER_VOL_GEPHI = f"{COFOUNDER}_{VOLUNTEERING}{GEPHI_EXT}"

EMPLOYEE_EDU_GEPHI = f"{EMPLOYEE}_{EDUCATION}{GEPHI_EXT}"
EMPLOYEE_EXP_GEPHI = f"{EMPLOYEE}_{EXPERIENCE}{GEPHI_EXT}"
EMPLOYEE_VOL_GEPHI = f"{EMPLOYEE}_{EDUCATION}{GEPHI_EXT}"

COFOUNDER_EMPLOYEE_GEPHI = f"{COFOUNDER}_{EMPLOYEE}{GEPHI_EXT}"

HTML_PATH = f"{DATA_PATH}/html"

JSON_PATH = f"{DATA_PATH}/json"
JSON_EXT = ".json"
INV_MANAGERS_JSON = f"investment_managers{JSON_EXT}"

COFOUNDER_EDU_JSON = f"{COFOUNDER}_{EDUCATION}{JSON_EXT}"
COFOUNDER_EXP_JSON = f"{COFOUNDER}_{EXPERIENCE}{JSON_EXT}"
COFOUNDER_VOL_JSON = f"{COFOUNDER}_{VOLUNTEERING}{JSON_EXT}"

EMPLOYEE_EDU_JSON = f"{EMPLOYEE}_{EDUCATION}{JSON_EXT}"
EMPLOYEE_EXP_JSON = f"{EMPLOYEE}_{EXPERIENCE}{JSON_EXT}"
EMPLOYEE_VOL_JSON = f"{EMPLOYEE}_{VOLUNTEERING}{JSON_EXT}"

STATE_PATH = "state"
LINKEDIN_STATE_FILE = "li_playwright_state.json"

LINKEDIN_CANONICAL_START = "https://www."
LINKEDIN_BASE = "linkedin.com"

LINKEDIN_LOGIN = f"{LINKEDIN_CANONICAL_START}{LINKEDIN_BASE}/login"

LINKEDIN_COMPANY_BASE = f"{LINKEDIN_BASE}/company/"
LINKEDIN_COMPANY_CANONICAL = f"{LINKEDIN_CANONICAL_START}{LINKEDIN_COMPANY_BASE}"

LINKEDIN_IN_BASE = f"{LINKEDIN_BASE}/in/"
LINKEDIN_IN_CANONICAL = f"{LINKEDIN_CANONICAL_START}{LINKEDIN_BASE}/in/"

LINKEDIN_404 = f"{LINKEDIN_BASE}/404"

# ---------- VCs ----------
BASE_212 = "https://212.vc"
PORTFOLIO_212 = f"{BASE_212}/portfolio"
TEAM_212 = f"{BASE_212}/team"