DATA_PATH = "data"

CSV_PATH = DATA_PATH + "/csv"

CSV_EXT = ".csv"

COFOUNDER_INVESTMENT = "cofounders_with_investment_managers"
COFOUNDER_INVESTMENT_CSV = COFOUNDER_INVESTMENT + CSV_EXT

PORTFOLIO = "portfolio_links"
PORTFOLIO_CSV = PORTFOLIO + CSV_EXT

TEAM = "employees_team"
TEAM_CSV = TEAM + CSV_EXT

TEAM_LINKEDIN = "employees_linkedin"
TEAM_LINKEDIN_CSV = TEAM_LINKEDIN + CSV_EXT

LOOKUP_LINKEDIN = "employee_lookup_linkedin"
LOOKUP_LINKEDIN_CSV = LOOKUP_LINKEDIN + CSV_EXT

COFOUNDER = "cofounders_linkedin"

COFOUNDER_MAIN = COFOUNDER + "_main"
COFOUNDER_MAIN_CSV = COFOUNDER_MAIN + CSV_EXT

COFOUNDER_EDU = COFOUNDER + "_education"
COFOUNDER_EDU_CSV = COFOUNDER_EDU + CSV_EXT

COFOUNDER_EXP = COFOUNDER + "_experience"
COFOUNDER_EXP_CSV = COFOUNDER_EXP + CSV_EXT

COFOUNDER_VOL = COFOUNDER + "_volunteering-experiences"
COFOUNDER_VOL_CSV = COFOUNDER_VOL + CSV_EXT

EMPLOYEE = "employee_linkedin"

EMPLOYEE_MAIN = EMPLOYEE + "_main"
EMPLOYEE_MAIN_CSV = EMPLOYEE_MAIN + CSV_EXT

EMPLOYEE_EDU = EMPLOYEE + "_education"
EMPLOYEE_EDU_CSV = EMPLOYEE_EDU + CSV_EXT

EMPLOYEE_EXP = EMPLOYEE + "_experience"
EMPLOYEE_EXP_CSV = EMPLOYEE_EXP + CSV_EXT

EMPLOYEE_VOL = EMPLOYEE + "_volunteering-experiences"
EMPLOYEE_VOL_CSV = EMPLOYEE_VOL + CSV_EXT

GEPHI_PATH = DATA_PATH + "/gephi"


HTML_PATH = DATA_PATH + "/html"
JSON_PATH = DATA_PATH + "/json"

STATE_PATH = "state"
LINKEDIN_STATE_FILE = "li_playwright_state.json"

LINKEDIN_CANONICAL_START = "https://www."
LINKEDIN_BASE = "linkedin.com"

LINKEDIN_LOGIN = LINKEDIN_CANONICAL_START + LINKEDIN_BASE + "/login"

LINKEDIN_COMPANY_BASE = LINKEDIN_BASE + "/company/"
LINKEDIN_COMPANY_CANONICAL = LINKEDIN_CANONICAL_START + LINKEDIN_COMPANY_BASE

LINKEDIN_IN_BASE = LINKEDIN_BASE + "/in/"
LINKEDIN_IN_CANONICAL = LINKEDIN_CANONICAL_START + LINKEDIN_BASE + "/in/"

LINKEDIN_404 = LINKEDIN_BASE + "/404"

# ---------- VCs ----------
BASE_212 = "https://212.vc"
PORTFOLIO_212 = BASE_212 + "/portfolio"
TEAM_212 = BASE_212 + "/team"